
# [START cloudbuild]
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud source repos clone  && \
    cd {REPONAME} && \
    git checkout master && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')



# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - '{REGION}-docker.pkg.dev/{PROJECT_ID}/{REGISTRY_REPO}/{BUILD_IMAGE_NAME}:latest'
  - '/workspace/{REPONAME}/web/'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - '{REGION}-docker.pkg.dev/{PROJECT_ID}/{REGISTRY_REPO}/{BUILD_IMAGE_NAME}:latest'


#Deploy image to K8s 
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=/workspace/k8s/apps/django-k8s-web.yaml
  - --image={REGION}-docker.pkg.dev/{PROJECT_ID}/{REGISTRY_REPO}/{BUILD_IMAGE_NAME}:latest
  - --location={REGION}
  - --cluster={CLUSTER_NAME}
