version: '3.9'
services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    image: django_k8s:v2
    environment:
      - PORT=8020
    env_file:
      - web/.env
    ports:
      - "8001:8020"
      
     
