apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
  labels:
    app: djang-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: djang-k8s-web-deployment
  template:
    metadata:
      labels:
        app: djang-k8s-web-deployment
    spec:
      containers:
      - name: django-k8s
        image: us-central1-docker.pkg.dev/production-api-enabill/artifact-k8s/django-k8s:latest
        envFrom:
          - secretRef:
              name: djang-k8s-web-prod-env
        env:
          - name: PORT
            value: "8001"
        ports:
        - containerPort: 8001
      imagePullSecrets:
        - name: artifact-registry

---

apiVersion: v1
kind: Service
metadata:
  name: djang-k8s-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http 
      protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: djang-k8s-web-deployment
